const areas=[['vocation','Vocation & Work'],['formation','Faith & Formation'],['home','House & Stewardship'],['finance','Finance & Administration'],['community','Community & Charity'],['renewal','Rest, Health & Renewal']].map(([id,name])=>({id,name}));
const statuses=['Active','Waiting','Maintenance','Seasonal','Paused','Complete'];
const ideaStages=['Captured','Worth exploring','Not before','Candidate project','Released'];
const anchorTypes=['Prayer','Body & Daily Life','Formation','Household Rhythm','Quies'];
const initialAnchors={Prayer:['Morning Prayer','Rosary','Evening Prayer','Night Prayer'],'Body & Daily Life':['Breakfast','Lunch','Dinner'],'Formation':['Reading'],'Household Rhythm':['Morning reset','Evening reset'],Quies:['Proper rest']};
const initialTools=[['Command','Plan A Tasks Workbook','Authoritative Helm registers','https://docs.google.com/spreadsheets/d/1Buu_wNEGEGv1yNxArA2R12sLjQiNO411bRP6xftvXWk'],['Files','Google Drive','Folders, records and masterlists','https://drive.google.com/drive/my-drive'],['Correspondence','Gmail','Primary correspondence','https://mail.google.com/mail/u/0/#inbox'],['Correspondence','Outlook','Microsoft correspondence','https://outlook.office.com/mail/'],['Planning','Google Calendar','Fixed commitments and protected time','https://calendar.google.com/calendar/u/0/r'],['Creation','GitHub','Sites, repositories and code','https://github.com/Wally189']].map((x,i)=>({id:'tool-'+i,group:x[0],name:x[1],note:x[2],url:x[3]}));
const seedProjects=[
{id:'weca',name:'WECA onboarding and preparation',area:'vocation',status:'Active',purpose:'Begin the Programme Coordinator role peacefully and well prepared.',phase:'Onboarding',position:'Offer accepted; onboarding and references are progressing.',next:'Complete the next requested onboarding action when approval arrives.',waiting:'Final confirmation and any remaining reference action.',reviewType:'Event',review:'When correspondence arrives',enough:'No further preparation is required today unless correspondence arrives.',masterlist:'https://drive.google.com/drive/folders/1AuhvIXaF1lb6t_kiIVtoMzffT7HJ7dSL'},
{id:'nbt',name:'NBT grievance and departure',area:'vocation',status:'Waiting',purpose:'Conclude employment justly, safely and with an accurate record.',phase:'Await and respond',position:'Resignation has been prepared while grievance matters remain live.',next:'Respond only to material correspondence or a required deadline.',waiting:'Employer response and any Stage 2 timetable.',reviewType:'Event',review:'On receipt of correspondence',enough:'The record is preserved. No repeated mental rehearsal is required.',masterlist:'https://drive.google.com/drive/folders/1tj5iUpyF0Lqv7v9N5fvXwjiO1euq4uS-'},
{id:'finance',name:'Financial stabilisation',area:'finance',status:'Active',purpose:'Protect essentials and move into the new employment period without disorder.',phase:'Stabilise',position:'A live household budget and debt-management folder are in place.',next:'Record confirmed income and pay only agreed priority items.',waiting:'Confirmed employment income and benefit decisions.',reviewType:'Recurring',review:'Weekly',enough:'Today is sufficient when the current balance and immediate obligations are known.',masterlist:'https://drive.google.com/drive/folders/14HF32X6VkC4steOV7mzQBeCnRMToUoCS'},
{id:'playtrix',name:'Playtrix and Helm',area:'home',status:'Active',purpose:'Create one dependable and calm working surface without losing Helm.',phase:'Test',position:'Playtrix is being rebuilt as the primary visual dashboard.',next:'Use the live version and record only real defects or friction.',waiting:'Direct Drive write-back remains a protected second stage.',reviewType:'Condition',review:'After several days of real use',enough:'Do not redesign merely because another idea occurs.',masterlist:'https://github.com/Wally189/waylight-playtrix'}];
const key='playtrix.marypoppins.v2';
const defaults={anchors:Object.fromEntries(anchorTypes.map(t=>[t,(initialAnchors[t]||[]).map((text,i)=>({id:t+i,text,done:false}))])),principal:'',supporting:[{id:'s1',text:'',done:false},{id:'s2',text:'',done:false}],maintenance:[],formation:[],stop:'',today:Object.fromEntries(areas.map(a=>[a.id,[]])),inbox:[],projects:seedProjects,ideas:[],tools:initialTools,weeklyNote:'',reviewedAt:'',tomorrowFirst:'',showOpening:true,lastOpened:'',closedAt:''};
let state=load(),selectedProject=null,statusFilter='All',menuTarget=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=v=>JSON.parse(JSON.stringify(v)),uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function load(){try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(!raw)return clone(defaults);return {...clone(defaults),...raw,anchors:{...clone(defaults.anchors),...(raw.anchors||{})},today:{...clone(defaults.today),...(raw.today||{})},projects:raw.projects?.length?raw.projects:clone(seedProjects),tools:raw.tools?.length?raw.tools:clone(initialTools)}}catch{return clone(defaults)}}
function save(){localStorage.setItem(key,JSON.stringify(state));renderCounts()}
function setView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='projects')renderProjects();if(id==='status')renderStatus();if(id==='notyet')renderIdeas();if(id==='tools')renderTools();scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function renderDate(){const d=new Date();$('#todayHeading').textContent=d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#liturgicalLine').textContent=d.getDay()===0?'The Lord’s Day':'Ordinary Time · Ora et labora'}
function renderAnchors(){const box=$('#anchorGroups');box.innerHTML='';anchorTypes.forEach(type=>{const group=document.createElement('section');group.className='anchor-group';group.innerHTML=`<header><h4>${type}</h4><button class="text-button">+ Add</button></header><div class="anchor-grid"></div>`;const grid=group.querySelector('.anchor-grid');(state.anchors[type]||[]).forEach((a,i)=>{const row=document.createElement('div');row.className='anchor';row.innerHTML=`<input type="checkbox" ${a.done?'checked':''}><label>${esc(a.text)}</label><button class="icon-button">×</button>`;row.children[0].onchange=e=>{a.done=e.target.checked;save()};row.children[2].onclick=()=>{state.anchors[type].splice(i,1);renderAnchors();save()};grid.append(row)});group.querySelector('header button').onclick=()=>{const text=prompt(`Add ${type} anchor`);if(text){state.anchors[type].push({id:uid('a'),text,done:false});renderAnchors();save()}};box.append(group)})}
function renderEditableList(selector,items,placeholder){const box=$(selector);box.innerHTML='';items.forEach((a,i)=>{const row=document.createElement('div');row.className='simple-row';row.innerHTML=`<input type="checkbox" ${a.done?'checked':''}><input type="text" value="${esc(a.text)}" placeholder="${placeholder}"><button class="icon-button">×</button>`;row.children[0].onchange=e=>{a.done=e.target.checked;save()};row.children[1].oninput=e=>{a.text=e.target.value;save()};row.children[2].onclick=()=>{items.splice(i,1);renderAllLists();save()};box.append(row)})}
function renderAllLists(){renderEditableList('#supportingList',state.supporting,'Supporting action');renderEditableList('#maintenanceList',state.maintenance,'House, garden or ordinary upkeep');renderEditableList('#formationList',state.formation,'Prayer, study or formation')}
function addListItem(list){state[list].push({id:uid(list),text:'',done:false});renderAllLists();save()}
$('#addSupporting').onclick=()=>addListItem('supporting');$('#addMaintenance').onclick=()=>addListItem('maintenance');$('#addFormation').onclick=()=>addListItem('formation');
function renderToday(){const box=$('#todayCategories');box.innerHTML='';areas.forEach(area=>{const card=document.createElement('section');card.className='category';card.innerHTML=`<h4>${area.name}</h4><div class="cat-list"></div><button class="text-button">+ Add here</button>`;const list=card.querySelector('.cat-list');(state.today[area.id]||[]).forEach(item=>{const row=document.createElement('div');row.className='task-row';row.innerHTML=`<input type="checkbox" ${item.done?'checked':''}><input type="text" value="${esc(item.text)}"><button class="icon-button">•••</button>`;row.children[0].onchange=e=>{item.done=e.target.checked;save()};row.children[1].oninput=e=>{item.text=e.target.value;save()};row.children[2].onclick=()=>{menuTarget={areaId:area.id,id:item.id};$('#itemMenu').showModal()};list.append(row)});card.querySelector('.text-button').onclick=()=>addTodayItem(area.id);box.append(card)})}
function addTodayItem(areaId){const text=prompt('What belongs on today’s page?');if(text){state.today[areaId].push({id:uid('day'),text,done:false,source:'local'});renderToday();save()}}
$('#removeToday').onclick=e=>{e.preventDefault();if(menuTarget){state.today[menuTarget.areaId]=state.today[menuTarget.areaId].filter(x=>x.id!==menuTarget.id);renderToday();save();$('#itemMenu').close()}};
$('#deleteItem').onclick=e=>{e.preventDefault();if(menuTarget&&confirm('Delete this local item?')){state.today[menuTarget.areaId]=state.today[menuTarget.areaId].filter(x=>x.id!==menuTarget.id);renderToday();save();$('#itemMenu').close()}};
function renderCounts(){$('#waitingCount').textContent=state.projects.filter(p=>p.status==='Waiting').length;$('#projectCount').textContent=state.projects.filter(p=>p.status==='Active').length;$('#inboxCount').textContent=state.inbox.length;$('#peaceState').textContent=state.inbox.length?'Capture waiting for triage':'In order'}
function renderProjects(){const list=$('#projectList');list.innerHTML='';state.projects.forEach(p=>{const b=document.createElement('button');b.className='project-button'+(selectedProject===p.id?' active':'');b.innerHTML=`<strong>${esc(p.name)}</strong><span>${esc(p.status)} · ${esc(p.phase||'No phase')}</span>`;b.onclick=()=>{selectedProject=p.id;renderProjects();renderProjectWorkspace(p)};list.append(b)});if(!selectedProject&&state.projects[0]){selectedProject=state.projects[0].id;renderProjects();renderProjectWorkspace(state.projects[0])}}
function renderProjectWorkspace(p){const box=$('#projectWorkspace');box.innerHTML=`<header class="project-head"><span class="eyebrow">${esc(p.status)}</span><h3>${esc(p.name)}</h3><p>${esc(p.purpose||'')}</p></header><div class="project-fields"><div class="project-field"><label>Name</label><input data-field="name" value="${esc(p.name)}"></div><div class="project-field"><label>Area</label><select data-field="area">${areas.map(a=>`<option value="${a.id}">${a.name}</option>`).join('')}</select></div><div class="project-field"><label>Phase</label><input data-field="phase" value="${esc(p.phase||'')}"></div><div class="project-field"><label>Status</label><select data-field="status">${statuses.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="project-field full"><label>Purpose</label><textarea data-field="purpose">${esc(p.purpose||'')}</textarea></div><div class="project-field full"><label>Present position</label><textarea data-field="position">${esc(p.position||'')}</textarea></div><div class="project-field"><label>Next physical action</label><textarea data-field="next">${esc(p.next||'')}</textarea></div><div class="project-field"><label>Waiting for</label><textarea data-field="waiting">${esc(p.waiting||'')}</textarea></div><div class="project-field"><label>Review trigger type</label><select data-field="reviewType"><option>Date</option><option>Recurring</option><option>Event</option><option>Condition</option><option>Phase end</option><option>No review before</option></select></div><div class="project-field"><label>Review trigger</label><input data-field="review" value="${esc(p.review||'')}"></div><div class="project-field full"><label>Enough for now</label><textarea data-field="enough">${esc(p.enough||'')}</textarea></div><div class="project-field full"><label>Masterlist / project desk</label><input data-field="masterlist" value="${esc(p.masterlist||'')}"></div></div><div class="project-actions"><a class="primary" href="${esc(p.masterlist||'#')}" target="_blank">Open masterlist</a><button class="danger" id="deleteProject">Remove project</button></div>`;box.querySelector('[data-field="area"]').value=p.area;box.querySelector('[data-field="status"]').value=p.status;box.querySelector('[data-field="reviewType"]').value=p.reviewType||'Date';box.querySelectorAll('[data-field]').forEach(el=>el.oninput=e=>{p[e.target.dataset.field]=e.target.value;save();if(['name','status','phase'].includes(e.target.dataset.field))renderProjects()});box.querySelector('#deleteProject').onclick=()=>{if(confirm('Remove this project from Playtrix?')){state.projects=state.projects.filter(x=>x.id!==p.id);selectedProject=null;renderProjects();save()}}}
$('#addProject').onclick=()=>{const name=prompt('Project name');if(name){state.projects.push({id:uid('p'),name,area:'vocation',status:'Active',purpose:'',phase:'Discern',position:'',next:'',waiting:'',reviewType:'Date',review:'',enough:'',masterlist:''});selectedProject=state.projects.at(-1).id;renderProjects();save()}};
function renderStatus(){const f=$('#statusFilters');f.innerHTML=['All',...statuses].map(s=>`<button class="${statusFilter===s?'active':''}">${s}</button>`).join('');[...f.children].forEach(b=>b.onclick=()=>{statusFilter=b.textContent;renderStatus()});const box=$('#statusList');const projects=state.projects.filter(p=>statusFilter==='All'||p.status===statusFilter);box.innerHTML=projects.length?'':'<p class="empty">No projects in this status.</p>';projects.forEach(p=>{const a=document.createElement('article');a.className='status-card';a.innerHTML=`<span class="eyebrow">${esc(p.status)} · ${esc(p.phase||'No phase')}</span><h3>${esc(p.name)}</h3><p>${esc(p.position||'No position recorded.')}</p><small><strong>Next:</strong> ${esc(p.next||'Not set')}<br><strong>Review:</strong> ${esc(p.reviewType||'Trigger')} — ${esc(p.review||'Not set')}</small>`;a.onclick=()=>{selectedProject=p.id;setView('projects')};box.append(a)})}
function renderIdeas(){const board=$('#kanban');board.innerHTML='';ideaStages.forEach(stage=>{const col=document.createElement('section');col.className='kanban-col';col.innerHTML=`<h3>${stage}</h3><div></div>`;state.ideas.filter(i=>i.stage===stage).forEach(idea=>{const card=document.createElement('article');card.className='idea';card.innerHTML=`<h4>${esc(idea.text)}</h4><p>${esc(idea.why||'')}</p><select>${ideaStages.map(s=>`<option>${s}</option>`).join('')}</select><button class="icon-button">×</button>`;card.querySelector('select').value=idea.stage;card.querySelector('select').onchange=e=>{idea.stage=e.target.value;renderIdeas();save()};card.querySelector('button').onclick=()=>{state.ideas=state.ideas.filter(x=>x.id!==idea.id);renderIdeas();save()};col.querySelector('div').append(card)});board.append(col)})}
$('#addIdea').onclick=()=>{const text=prompt('What idea should be kept safely?');if(text){state.ideas.push({id:uid('idea'),text,why:prompt('Why might it matter?')||'',stage:'Captured'});renderIdeas();save()}};
function moveTool(i,delta){const n=i+delta;if(n<0||n>=state.tools.length)return;[state.tools[i],state.tools[n]]=[state.tools[n],state.tools[i]];renderTools();save()}
function renderTools(){const box=$('#toolGroups');box.innerHTML='';[...new Set(state.tools.map(t=>t.group))].forEach(group=>{const sec=document.createElement('section');sec.className='tool-group';sec.innerHTML=`<h3>${esc(group)}</h3><div></div>`;state.tools.filter(t=>t.group===group).forEach(tool=>{const i=state.tools.indexOf(tool),card=document.createElement('article');card.className='desk-card';card.innerHTML=`<div><h4>${esc(tool.name)}</h4><p>${esc(tool.note)}</p></div><div class="tool-actions"><button>↑</button><button>↓</button><a class="ghost" href="${esc(tool.url)}" target="_blank">Open</a><button class="icon-button">×</button></div>`;const bs=card.querySelectorAll('button');bs[0].onclick=()=>moveTool(i,-1);bs[1].onclick=()=>moveTool(i,1);bs[2].onclick=()=>{state.tools.splice(i,1);renderTools();save()};sec.querySelector('div').append(card)});box.append(sec)})}
$('#addTool').onclick=()=>{const name=prompt('Tool or desk name');if(!name)return;const group=prompt('Group: Command, Correspondence, Files, Planning, Creation, Learning or another name','Command')||'Other';const url=prompt('Full web address')||'#';const note=prompt('Brief description')||'';state.tools.push({id:uid('tool'),group,name,note,url});renderTools();save()};
function openCapture(){$('#captureText').value='';$('#captureDialog').showModal()}$('#captureButton').onclick=openCapture;$('#mobileCapture').onclick=openCapture;$('#captureArea').innerHTML=areas.map(a=>`<option value="${a.id}">${a.name}</option>`).join('');
$('#saveCapture').onclick=e=>{e.preventDefault();const text=$('#captureText').value.trim(),kind=$('#captureKind').value,area=$('#captureArea').value;if(!text)return;if(kind==='idea')state.ideas.push({id:uid('idea'),text,why:'',stage:'Captured'});else if(kind==='action')state.today[area].push({id:uid('day'),text,done:false,source:'local'});else state.inbox.push({id:uid('cap'),text,kind,area});save();renderToday();renderIdeas();$('#captureDialog').close()};
$('#addToday').onclick=()=>{const n=Number(prompt(areas.map((a,i)=>`${i+1}. ${a.name}`).join('\n')))-1;if(areas[n])addTodayItem(areas[n].id)};
$('#principalWork').oninput=e=>{state.principal=e.target.value;save()};$('#stopCondition').oninput=e=>{state.stop=e.target.value;save()};$('#weeklyNote').oninput=e=>{state.weeklyNote=e.target.value;save()};
$('#closeDay').onclick=()=>{$('#tomorrowFirst').value=state.tomorrowFirst||'';$('#closing').classList.remove('hidden')};$('#markReviewed').onclick=()=>{$('#tomorrowFirst').value=state.tomorrowFirst||'';state.reviewedAt=new Date().toISOString();save();renderReviewStamp();$('#closing').classList.remove('hidden')};$('#returnDashboard').onclick=()=>$('#closing').classList.add('hidden');$('#finishClosing').onclick=()=>{state.tomorrowFirst=$('#tomorrowFirst').value.trim();state.closedAt=new Date().toISOString();save();$('#closing').classList.add('hidden');document.body.innerHTML='<main class="closed"><h1>The day is closed.</h1><p>The record is sufficient. Go in peace.</p></main>'};
function renderReviewStamp(){if(state.reviewedAt)$('#reviewStamp').textContent=`Last restored: ${new Date(state.reviewedAt).toLocaleString('en-GB')}`}
function opening(){const today=new Date().toISOString().slice(0,10),show=state.showOpening&&state.lastOpened!==today;$('#opening').classList.toggle('hidden',!show);$('#showOpening').checked=state.showOpening}$('#beginDay').onclick=$('#skipOpening').onclick=()=>{state.showOpening=$('#showOpening').checked;state.lastOpened=new Date().toISOString().slice(0,10);save();$('#opening').classList.add('hidden')};
function init(){renderDate();renderAnchors();renderAllLists();renderToday();renderProjects();renderStatus();renderIdeas();renderTools();renderCounts();$('#principalWork').value=state.principal;$('#stopCondition').value=state.stop;$('#weeklyNote').value=state.weeklyNote;renderReviewStamp();opening()}init();