const sections=[
{id:'vocation',number:'01',name:'Vocation & Work',purpose:'Employment, calling, boundaries, obligations and purposeful work.'},
{id:'formation',number:'02',name:'Faith & Formation',purpose:'Prayer, study, experiments, reading and development.'},
{id:'stewardship',number:'03',name:'Household & Stewardship',purpose:'Finances, home, administration and practical order.'},
{id:'community',number:'04',name:'Community & Relationship',purpose:'Family, friends, parish, civic life and service.'},
{id:'renewal',number:'05',name:'Rest & Renewal',purpose:'Leisure, recovery, hobbies and proper stopping.'},
{id:'health',number:'06',name:'Health & Personal',purpose:'Health, routines and essential private instructions.'}
];
const launchers=[
{name:'Google Drive',url:'https://drive.google.com/drive/my-drive',note:'Folders and source documents'},
{name:'Gmail · account 1',url:'https://mail.google.com/mail/u/0/#inbox',note:'Primary Gmail desk'},
{name:'Gmail · account 2',url:'https://mail.google.com/mail/u/1/#inbox',note:'Second Gmail desk'},
{name:'Microsoft 365',url:'https://www.office.com/',note:'Office home and apps'},
{name:'Outlook',url:'https://outlook.office.com/mail/',note:'Microsoft email'},
{name:'OneDrive',url:'https://onedrive.live.com/',note:'Microsoft files'},
{name:'Google Calendar',url:'https://calendar.google.com/calendar/u/0/r',note:'Fixed commitments'},
{name:'GitHub',url:'https://github.com/Wally189',note:'Sites and code'}
];
const key='playtrix.helm.v1';
const defaults={focus:'',today:[{text:'',done:false},{text:'',done:false},{text:'',done:false}],inbox:[],sections:{}};
sections.forEach(s=>defaults.sections[s.id]={position:'',actions:[],waiting:[],links:[]});
let state=load();let currentSection=null;
function load(){try{return merge(defaults,JSON.parse(localStorage.getItem(key)||'{}'))}catch{return structuredClone(defaults)}}
function merge(base,extra){const out=structuredClone(base);Object.assign(out,extra);out.sections=out.sections||{};sections.forEach(s=>out.sections[s.id]=Object.assign({},base.sections[s.id],extra.sections?.[s.id]||{}));return out}
function save(){localStorage.setItem(key,JSON.stringify(state));renderSignals()}
const $=s=>document.querySelector(s);
function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===id.replace('#','')));scrollTo({top:0,behavior:'smooth'})}
function renderFront(){const d=new Date();$('#todayHeading').textContent=d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'});$('#principalFocus').value=state.focus;$('#todayList').innerHTML='';state.today.forEach((item,i)=>{const row=document.createElement('div');row.className='task-row';row.innerHTML=`<input type="checkbox" ${item.done?'checked':''} aria-label="Complete task"><input type="text" value="${esc(item.text)}" placeholder="${['Essential outcome','Useful outcome','Small outcome'][i]}">`;const [check,text]=row.querySelectorAll('input');check.onchange=()=>{state.today[i].done=check.checked;save()};text.oninput=()=>{state.today[i].text=text.value;save()};$('#todayList').append(row)});$('#sectionCards').innerHTML=sections.map(s=>`<article class="card section-card" data-section="${s.id}"><p class="eyebrow">${s.number}</p><strong>${s.name}</strong><p class="muted">${s.purpose}</p></article>`).join('');document.querySelectorAll('[data-section]').forEach(c=>c.onclick=()=>openSection(c.dataset.section));$('#launcherGrid').innerHTML=launchers.map((l,i)=>`<div class="launcher"><strong>${l.name}</strong><span class="muted">${l.note}</span><div class="launcher-actions"><button data-viewer="${i}">View here</button><a href="${l.url}" target="_blank" rel="noopener">Open app</a></div></div>`).join('');document.querySelectorAll('[data-viewer]').forEach(b=>b.onclick=()=>openViewer(launchers[+b.dataset.viewer]));renderSignals()}
function renderSignals(){const allWaiting=sections.flatMap(s=>state.sections[s.id].waiting||[]);$('#waitingCount').textContent=allWaiting.length;$('#inboxCount').textContent=state.inbox.length;const dated=allWaiting.filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date));$('#nearestDeadline').textContent=dated[0]?.date||'Not set'}
function openSection(id){currentSection=id;const s=sections.find(x=>x.id===id),data=state.sections[id];$('#sectionNumber').textContent=s.number;$('#sectionName').textContent=s.name;$('#sectionPurpose').textContent=s.purpose;$('#sectionPosition').value=data.position;renderItems('#sectionActions',data.actions,'Next action');renderItems('#sectionWaiting',data.waiting,'Waiting for');renderLinks();setView('#sectionView')}
function renderItems(selector,items,placeholder){const box=$(selector);box.innerHTML='';items.forEach((item,i)=>{const row=document.createElement('div');row.className='waiting-row';row.innerHTML=`<input value="${esc(item.text||'')}" placeholder="${placeholder}"><button class="back-button" aria-label="Delete">×</button>`;row.querySelector('input').oninput=e=>{item.text=e.target.value;save()};row.querySelector('button').onclick=()=>{items.splice(i,1);openSection(currentSection);save()};box.append(row)})}
function renderLinks(){const links=state.sections[currentSection].links;$('#sectionLinks').innerHTML='';links.forEach((link,i)=>{const row=document.createElement('div');row.className='link-item';row.innerHTML=`<a href="${esc(link.url)}" target="_blank" rel="noopener">${esc(link.name)}</a><button class="back-button">×</button>`;row.querySelector('button').onclick=()=>{links.splice(i,1);renderLinks();save()};$('#sectionLinks').append(row)})}
function addItem(kind){const text=prompt(kind==='actions'?'What is the next action?':'What are you waiting for?');if(text){state.sections[currentSection][kind].push({text});openSection(currentSection);save()}}
function openViewer(item){$('#viewerTitle').textContent=item.name;$('#viewerExternal').href=item.url;$('#viewerFrame').src=item.url;setView('#viewerView')}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#principalFocus').oninput=e=>{state.focus=e.target.value;save()};$('#captureButton').onclick=()=>$('#captureDialog').showModal();$('#captureSection').innerHTML='<option value="inbox">General inbox</option>'+sections.map(s=>`<option value="${s.id}">${s.number} ${s.name}</option>`).join('');$('#saveCapture').onclick=e=>{e.preventDefault();const text=$('#captureText').value.trim(),section=$('#captureSection').value;if(!text)return;if(section==='inbox')state.inbox.push({text,created:new Date().toISOString()});else state.sections[section].actions.push({text});$('#captureText').value='';save();$('#captureDialog').close();renderFront()};$('#backButton').onclick=()=>setView('#front');$('#viewerBack').onclick=()=>setView('#front');$('#addAction').onclick=()=>addItem('actions');$('#addWaiting').onclick=()=>addItem('waiting');$('#addLink').onclick=()=>{const name=prompt('Link name');if(!name)return;const url=prompt('Paste the full web address');if(url){state.sections[currentSection].links.push({name,url});renderLinks();save()}};$('#sectionPosition').oninput=e=>{state.sections[currentSection].position=e.target.value;save()};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>t.dataset.view==='front'?setView('#front'):openSection(t.dataset.view));renderFront();