const areas=[
{id:'vocation',name:'Vocation & Work'},
{id:'formation',name:'Faith & Formation'},
{id:'home',name:'House & Stewardship'},
{id:'finance',name:'Finance & Administration'},
{id:'community',name:'Community & Charity'},
{id:'renewal',name:'Rest, Health & Renewal'}
];
const desks=[
{name:'Plan A Tasks Workbook',note:'Authoritative live registers for Helm',url:'https://docs.google.com/spreadsheets/d/1Buu_wNEGEGv1yNxArA2R12sLjQiNO411bRP6xftvXWk'},
{name:'Google Drive',note:'Source documents, folders and records',url:'https://drive.google.com/drive/my-drive'},
{name:'Gmail',note:'Primary correspondence desk',url:'https://mail.google.com/mail/u/0/#inbox'},
{name:'Outlook',note:'Microsoft correspondence',url:'https://outlook.office.com/mail/'},
{name:'Google Calendar',note:'Fixed commitments and protected time',url:'https://calendar.google.com/calendar/u/0/r'},
{name:'GitHub',note:'Sites, repositories and code',url:'https://github.com/Wally189'}
];
const defaultAnchors=['Morning Prayer','Evening Prayer','Rosary','Night Prayer','Reading','Breakfast','Lunch','Dinner','House reset','Proper rest'];
const seedProjects=[
{id:'weca',name:'WECA onboarding and preparation',area:'vocation',status:'Active',purpose:'Begin the Programme Coordinator role peacefully and well prepared.',position:'Offer accepted; onboarding and references are progressing.',next:'Complete the next requested onboarding action when approval arrives.',waiting:'Final confirmation and any remaining reference action.',review:'Next working day',enough:'No further preparation is required today unless correspondence arrives.',desk:'https://drive.google.com/drive/folders/1AuhvIXaF1lb6t_kiIVtoMzffT7HJ7dSL'},
{id:'nbt',name:'NBT grievance and departure',area:'vocation',status:'Waiting',purpose:'Conclude employment justly, safely and with an accurate record.',position:'Resignation has been prepared while grievance matters remain live.',next:'Respond only to material correspondence or a required deadline.',waiting:'Employer response and any Stage 2 timetable.',review:'On receipt or next dated review',enough:'The record is preserved. No repeated mental rehearsal is required.',desk:'https://drive.google.com/drive/folders/1tj5iUpyF0Lqv7v9N5fvXwjiO1euq4uS-'},
{id:'finance',name:'Financial stabilisation',area:'finance',status:'Active',purpose:'Protect essentials and move into the new employment period without disorder.',position:'A live household budget and debt-management folder are in place.',next:'Record confirmed income and pay only the agreed priority items.',waiting:'Confirmed employment income and benefit decisions.',review:'Weekly',enough:'Today is sufficient when the current balance and immediate obligations are known.',desk:'https://drive.google.com/drive/folders/14HF32X6VkC4steOV7mzQBeCnRMToUoCS'},
{id:'playtrix',name:'Playtrix and Helm',area:'home',status:'Active',purpose:'Create one dependable and calm working surface without losing Helm.',position:'Playtrix is being rebuilt as the primary visual dashboard.',next:'Use the live version and note only defects or genuine friction.',waiting:'Direct Drive write-back remains a protected second stage.',review:'After several days of real use',enough:'Do not redesign merely because another idea occurs.',desk:'https://github.com/Wally189/waylight-playtrix'}
];
const key='playtrix.marypoppins.v1';
const emptyToday=()=>Object.fromEntries(areas.map(a=>[a.id,[]]));
const defaults={anchors:defaultAnchors.map(text=>({text,done:false})),principal:'',supporting:[{text:'',done:false},{text:'',done:false}],maintenance:'',formation:'',stop:'',today:emptyToday(),inbox:[],projects:seedProjects,ideas:[],weeklyNote:'',reviewedAt:'',tomorrowFirst:'',closedAt:''};
let state=load();
let selectedProject=null;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(!raw)return clone(defaults);return {...clone(defaults),...raw,today:{...emptyToday(),...(raw.today||{})},projects:raw.projects?.length?raw.projects:clone(seedProjects)}}catch{return clone(defaults)}}
function save(){localStorage.setItem(key,JSON.stringify(state));renderCounts()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function uid(prefix='i'){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function setView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='projects')renderProjects();if(id==='waiting')renderWaiting();if(id==='notyet')renderIdeas();if(id==='desks')renderDesks();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
function renderDate(){const d=new Date();$('#todayHeading').textContent=d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const sunday=d.getDay()===0;$('#liturgicalLine').textContent=sunday?'The Lord’s Day':'Ordinary Time · Ora et labora';if(sunday){$('#dayQuote').textContent='The Sabbath was made for man, not man for the Sabbath.'}}
function renderAnchors(){const box=$('#anchorsList');box.innerHTML='';state.anchors.forEach((a,i)=>{const row=document.createElement('div');row.className='anchor';row.innerHTML=`<input type="checkbox" ${a.done?'checked':''}><label>${esc(a.text)}</label><button class="icon-button" aria-label="Remove">×</button>`;row.children[0].onchange=e=>{a.done=e.target.checked;save()};row.children[2].onclick=()=>{state.anchors.splice(i,1);renderAnchors();save()};box.append(row)});const add=document.createElement('button');add.className='anchor ghost';add.textContent='+ Anchor';add.onclick=()=>{const text=prompt('New anchor');if(text){state.anchors.push({text,done:false});renderAnchors();save()}};box.append(add)}
function renderSupporting(){const box=$('#supportingList');box.innerHTML='';state.supporting.forEach((a,i)=>{const row=document.createElement('div');row.className='simple-row';row.innerHTML=`<input type="checkbox" ${a.done?'checked':''}><input type="text" value="${esc(a.text)}" placeholder="Supporting action ${i+1}">`;row.children[0].onchange=e=>{a.done=e.target.checked;save()};row.children[1].oninput=e=>{a.text=e.target.value;save()};box.append(row)})}
function renderToday(){const box=$('#todayCategories');box.innerHTML='';areas.forEach(area=>{const card=document.createElement('section');card.className='category';card.innerHTML=`<h4>${area.name}</h4><div class="cat-list"></div><button>+ Add here</button>`;const list=card.querySelector('.cat-list');(state.today[area.id]||[]).forEach((item,i)=>{const row=document.createElement('div');row.className='task-row';row.innerHTML=`<input type="checkbox" ${item.done?'checked':''}><input type="text" value="${esc(item.text)}"><button aria-label="Remove">×</button>`;row.children[0].onchange=e=>{item.done=e.target.checked;save()};row.children[1].oninput=e=>{item.text=e.target.value;save()};row.children[2].onclick=()=>{state.today[area.id].splice(i,1);renderToday();save()};list.append(row)});card.querySelector('button:last-child').onclick=()=>addTodayItem(area.id);box.append(card)})}
function addTodayItem(areaId){const text=prompt('What belongs on today’s page?');if(text){state.today[areaId].push({id:uid('day'),text,done:false});renderToday();save()}}
function renderCounts(){const waiting=state.projects.filter(p=>p.waiting?.trim()).length+state.inbox.filter(x=>x.kind==='waiting').length;$('#waitingCount').textContent=waiting;$('#projectCount').textContent=state.projects.filter(p=>p.status==='Active'||p.status==='Waiting').length;$('#inboxCount').textContent=state.inbox.length;const loose=state.inbox.length;$('#peaceState').textContent=loose?'Capture waiting for triage':'In order'}
function renderProjects(){const list=$('#projectList');list.innerHTML='';state.projects.forEach(p=>{const b=document.createElement('button');b.className='project-button'+(selectedProject===p.id?' active':'');b.innerHTML=`<strong>${esc(p.name)}</strong><span>${esc(p.status)} · ${esc(areas.find(a=>a.id===p.area)?.name||'Project')}</span>`;b.onclick=()=>{selectedProject=p.id;renderProjects();renderProjectWorkspace(p)};list.append(b)});if(!selectedProject&&state.projects[0]){selectedProject=state.projects[0].id;renderProjects();renderProjectWorkspace(state.projects[0])}}
function renderProjectWorkspace(p){const box=$('#projectWorkspace');box.innerHTML=`<header class="project-head"><span class="eyebrow">${esc(p.status)}</span><h3>${esc(p.name)}</h3><p>${esc(p.purpose||'')}</p></header><div class="project-fields">
<div class="project-field full"><label>Present position</label><textarea rows="3" data-field="position">${esc(p.position||'')}</textarea></div>
<div class="project-field"><label>Next physical action</label><textarea rows="3" data-field="next">${esc(p.next||'')}</textarea></div>
<div class="project-field"><label>Waiting for</label><textarea rows="3" data-field="waiting">${esc(p.waiting||'')}</textarea></div>
<div class="project-field"><label>Review trigger</label><input data-field="review" value="${esc(p.review||'')}"></div>
<div class="project-field"><label>Status</label><select data-field="status"><option>Active</option><option>Waiting</option><option>Maintenance</option><option>Seasonal</option><option>Paused</option><option>Complete</option></select></div>
<div class="project-field full"><label>Enough for now</label><textarea rows="3" data-field="enough">${esc(p.enough||'')}</textarea></div></div><div class="project-actions"><a class="primary" href="${esc(p.desk||'#')}" target="_blank" rel="noopener">Open desk</a><button class="ghost" id="deleteProject">Remove project</button></div>`;
box.querySelector('[data-field="status"]').value=p.status;box.querySelectorAll('[data-field]').forEach(el=>el.oninput=e=>{p[e.target.dataset.field]=e.target.value;save()});box.querySelector('#deleteProject').onclick=()=>{if(confirm('Remove this project from Playtrix?')){state.projects=state.projects.filter(x=>x.id!==p.id);selectedProject=null;renderProjects();save()}}}
function renderWaiting(){const box=$('#waitingList');box.innerHTML='';const items=[...state.projects.filter(p=>p.waiting?.trim()).map(p=>({title:p.name,text:p.waiting,review:p.review,enough:p.enough})),...state.inbox.filter(x=>x.kind==='waiting').map(x=>({title:areas.find(a=>a.id===x.area)?.name||'Waiting',text:x.text,review:'Captured item',enough:'No action until the trigger occurs.'}))];if(!items.length){box.innerHTML='<p class="empty">Nothing is waiting.</p>';return}items.forEach(x=>{const a=document.createElement('article');a.innerHTML=`<h3>${esc(x.title)}</h3><p>${esc(x.text)}</p><small><strong>Review:</strong> ${esc(x.review||'Not set')} · <strong>Enough for now:</strong> ${esc(x.enough||'No further action today.')}</small>`;box.append(a)})}
function renderIdeas(){const box=$('#ideaGrid');box.innerHTML='';if(!state.ideas.length){box.innerHTML='<p class="empty">No ideas are being held. The space may remain empty.</p>';return}state.ideas.forEach((idea,i)=>{const card=document.createElement('article');card.className='idea';card.innerHTML=`<span class="eyebrow">Not yet</span><h3>${esc(idea.text)}</h3><p>${esc(idea.why||'Kept safely without becoming an obligation.')}</p><footer><small>Review: ${esc(idea.review||'When capacity exists')}</small><button class="icon-button">×</button></footer>`;card.querySelector('button').onclick=()=>{state.ideas.splice(i,1);renderIdeas();save()};box.append(card)})}
function renderDesks(){const box=$('#deskGrid');box.innerHTML=desks.map(d=>`<article class="desk-card"><div><h3>${esc(d.name)}</h3><p>${esc(d.note)}</p></div><a class="ghost" href="${d.url}" target="_blank" rel="noopener">Open</a></article>`).join('')}
function openCapture(){const dialog=$('#captureDialog');$('#captureText').value='';dialog.showModal()}
$('#captureButton').onclick=openCapture;$('#mobileCapture').onclick=openCapture;
$('#captureArea').innerHTML=areas.map(a=>`<option value="${a.id}">${a.name}</option>`).join('');
$('#saveCapture').onclick=e=>{e.preventDefault();const text=$('#captureText').value.trim();if(!text)return;const kind=$('#captureKind').value,area=$('#captureArea').value;if(kind==='idea'){state.ideas.push({id:uid('idea'),text,why:'',review:'When capacity exists'})}else if(kind==='action'){state.today[area].push({id:uid('day'),text,done:false})}else{state.inbox.push({id:uid('cap'),text,kind,area,created:new Date().toISOString()})}save();renderToday();renderIdeas();$('#captureDialog').close()};
$('#addToday').onclick=()=>{const area=prompt(`Area: ${areas.map((a,i)=>`${i+1} ${a.name}`).join(', ')}`);const n=Number(area)-1;if(areas[n])addTodayItem(areas[n].id)};
$('#addIdea').onclick=()=>{const text=prompt('What idea should be kept safely?');if(text){const why=prompt('Why might it matter?')||'';state.ideas.push({id:uid('idea'),text,why,review:'When capacity exists'});renderIdeas();save()}};
$('#principalWork').oninput=e=>{state.principal=e.target.value;save()};$('#maintenanceTask').oninput=e=>{state.maintenance=e.target.value;save()};$('#formationTask').oninput=e=>{state.formation=e.target.value;save()};$('#stopCondition').oninput=e=>{state.stop=e.target.value;save()};$('#weeklyNote').oninput=e=>{state.weeklyNote=e.target.value;save()};
$('#closeDay').onclick=()=>{$('#tomorrowFirst').value=state.tomorrowFirst||'';$('#closeDialog').showModal()};
$('#confirmClose').onclick=e=>{e.preventDefault();state.tomorrowFirst=$('#tomorrowFirst').value.trim();state.closedAt=new Date().toISOString();save();$('#closeDialog').close();alert('The record is sufficient. The day may now be closed.')};
$('#markReviewed').onclick=()=>{state.reviewedAt=new Date().toISOString();save();renderReviewStamp()};
function renderReviewStamp(){if(state.reviewedAt)$('#reviewStamp').textContent=`Last restored: ${new Date(state.reviewedAt).toLocaleString('en-GB')}`}
function initialise(){renderDate();renderAnchors();renderSupporting();renderToday();renderProjects();renderWaiting();renderIdeas();renderDesks();renderCounts();$('#principalWork').value=state.principal;$('#maintenanceTask').value=state.maintenance;$('#formationTask').value=state.formation;$('#stopCondition').value=state.stop;$('#weeklyNote').value=state.weeklyNote;renderReviewStamp()}
initialise();