'use strict';
document.addEventListener('DOMContentLoaded',()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='playtrix.organiser.v2',VERSION=2;
const blank=()=>({version:VERSION,principal:'',supporting:[],maintenance:[],formation:[],stop:'',tasks:[],projects:[],waiting:[],ideas:[],tools:[],captures:[],weeklyNote:'',lastReviewed:'',tomorrowFirst:''});
let st=blank();
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(parsed&&typeof parsed==='object'&&parsed.version===VERSION)st={...blank(),...parsed};}}catch(e){}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(st));return true}catch(e){status('Browser storage is unavailable or full. Export your data if possible.');return false}};
const id=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const status=t=>{const el=q('#settingsStatus');if(el)el.textContent=t};
function show(v){qa('.view').forEach(x=>x.classList.toggle('active',x.id===v));qa('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));renderAll();scrollTo(0,0)}qa('[data-view]').forEach(x=>x.onclick=()=>show(x.dataset.view));
q('#todayHeading').textContent=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
function rows(sel,list,placeholder){const b=q(sel);b.innerHTML='';list.forEach((x,i)=>{const r=document.createElement('div');r.className='simple-row';r.innerHTML=`<input aria-label="Complete" type="checkbox"><input value="${esc(x)}" placeholder="${esc(placeholder)}"><button type="button" class="icon-button" aria-label="Delete">×</button>`;r.children[1].oninput=e=>{list[i]=e.target.value;save()};r.children[2].onclick=()=>{list.splice(i,1);renderToday();save()};b.append(r)})}
function renderToday(){rows('#supportingList',st.supporting,'Supporting action');rows('#maintenanceList',st.maintenance,'Life admin or upkeep');rows('#formationList',st.formation,'Learning item');q('#principalWork').value=st.principal;q('#stopCondition').value=st.stop;q('#taskCount').textContent=st.tasks.filter(x=>x.status!=='Complete').length;q('#waitingCount').textContent=st.waiting.length;q('#projectCount').textContent=st.projects.filter(x=>x.status!=='Complete').length;q('#inboxCount').textContent=st.captures.length}
q('#principalWork').oninput=e=>{st.principal=e.target.value;save()};q('#stopCondition').oninput=e=>{st.stop=e.target.value;save()};q('#addSupporting').onclick=()=>{st.supporting.push('');renderToday();save()};q('#addMaintenance').onclick=()=>{st.maintenance.push('');renderToday();save()};q('#addFormation').onclick=()=>{st.formation.push('');renderToday();save()};
function card(item,type){const a=document.createElement('article');a.className='status-card';a.innerHTML=`<span class="eyebrow">${esc(item.status||type)}</span><h3>${esc(item.text||item.name)}</h3>${item.notes?`<p>${esc(item.notes)}</p>`:''}${item.review?`<small><strong>Review:</strong> ${esc(item.review)}</small>`:''}<div class="dialog-actions"><button class="ghost edit">Edit</button><button class="danger del">Delete</button></div>`;a.querySelector('.edit').onclick=()=>openEdit(type,item);a.querySelector('.del').onclick=()=>{if(confirm('Delete this item?')){const arr=type==='task'?st.tasks:type==='waiting'?st.waiting:st.projects;arr.splice(arr.findIndex(x=>x.id===item.id),1);save();renderAll()}};return a}
function renderTasks(){const b=q('#taskList');b.innerHTML='';st.tasks.forEach(x=>b.append(card(x,'task')))}
function renderWaiting(){const b=q('#waitingList');b.innerHTML='';st.waiting.forEach(x=>b.append(card(x,'waiting')))}
function renderProjects(){const l=q('#projectList');l.innerHTML='';st.projects.forEach(p=>{const b=document.createElement('button');b.className='project-button';b.innerHTML=`<strong>${esc(p.name)}</strong><span>${esc(p.status)}</span>`;b.onclick=()=>{const w=q('#projectWorkspace');w.innerHTML='';w.append(card(p,'project'))};l.append(b)});if(!st.projects.length)q('#projectWorkspace').innerHTML='<p class="empty">No projects yet.</p>'}
const stages=['Captured','Exploring','Not before','Candidate project','Released'];
function renderIdeas(){const b=q('#kanban');b.innerHTML='';stages.forEach(stage=>{const c=document.createElement('section');c.className='kanban-col';c.innerHTML=`<h3>${stage}</h3><div></div>`;st.ideas.filter(x=>x.stage===stage).forEach(x=>{const a=document.createElement('article');a.className='idea';a.innerHTML=`<h4>${esc(x.text)}</h4><select aria-label="Idea stage">${stages.map(y=>`<option>${y}</option>`).join('')}</select><button class="danger">Delete</button>`;a.querySelector('select').value=x.stage;a.querySelector('select').onchange=e=>{x.stage=e.target.value;save();renderIdeas()};a.querySelector('button').onclick=()=>{st.ideas=st.ideas.filter(y=>y.id!==x.id);save();renderIdeas()};c.querySelector('div').append(a)});b.append(c)})}
function renderTools(){const b=q('#toolGroups');b.innerHTML='';if(!st.tools.length){b.innerHTML='<p class="empty">Add links to the tools and workspaces you use.</p>';return}st.tools.forEach(x=>{const a=document.createElement('article');a.className='desk-card';a.innerHTML=`<div><h4>${esc(x.name)}</h4><small>${esc(x.url)}</small></div><div><a class="ghost" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open</a> <button class="danger">Delete</button></div>`;a.querySelector('button').onclick=()=>{st.tools=st.tools.filter(y=>y.id!==x.id);save();renderTools()};b.append(a)})}
q('#addTask').onclick=()=>{const x=prompt('Task');if(x){st.tasks.unshift({id:id(),text:x,status:'Active',notes:'',review:'',createdAt:new Date().toISOString()});save();renderAll()}};
q('#addWaiting').onclick=()=>{const x=prompt('What are you waiting for?');if(x){st.waiting.unshift({id:id(),text:x,status:'Waiting',notes:'',review:'',createdAt:new Date().toISOString()});save();renderAll()}};
q('#addProject').onclick=()=>{const x=prompt('Project name');if(x){st.projects.unshift({id:id(),name:x,status:'Active',notes:'',review:'',createdAt:new Date().toISOString()});save();renderAll()}};
q('#addIdea').onclick=()=>{const x=prompt('Idea');if(x){st.ideas.unshift({id:id(),text:x,stage:'Captured'});save();renderIdeas()}};
q('#addTool').onclick=()=>{const name=prompt('Tool name');if(!name)return;const url=prompt('Web address (https://...)');if(!url)return;try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw 0;st.tools.push({id:id(),name,url:u.href});save();renderTools()}catch(e){alert('Please enter a valid http or https address.')}};
let editCtx=null;function openEdit(type,item){editCtx={type,item};q('#editTitle').textContent=`Edit ${type}`;q('#editText').value=item.text||item.name||'';q('#editNotes').value=item.notes||'';q('#editReview').value=item.review||'';const opts=type==='project'?['Active','Waiting','Maintenance','Paused','Complete']:type==='task'?['Active','Waiting','Complete']:['Waiting','Complete'];q('#editStatus').innerHTML=opts.map(x=>`<option>${x}</option>`).join('');q('#editStatus').value=item.status||opts[0];q('#editDialog').showModal()}
q('#saveEdit').onclick=e=>{e.preventDefault();if(!editCtx)return;const {type,item}=editCtx;const text=q('#editText').value.trim();if(!text)return;if(type==='project')item.name=text;else item.text=text;item.notes=q('#editNotes').value.trim();item.review=q('#editReview').value.trim();item.status=q('#editStatus').value;item.updatedAt=new Date().toISOString();save();q('#editDialog').close();renderAll()};
const cap=()=>q('#captureDialog').showModal();q('#captureButton').onclick=cap;q('#mobileCapture').onclick=cap;q('#saveCapture').onclick=e=>{e.preventDefault();const text=q('#captureText').value.trim();if(!text)return;const kind=q('#captureKind').value,area=q('#captureArea').value.trim(),base={id:id(),text,area,notes:'',review:'',createdAt:new Date().toISOString()};if(kind==='task')st.tasks.unshift({...base,status:'Active'});else if(kind==='waiting')st.waiting.unshift({...base,status:'Waiting'});else if(kind==='idea')st.ideas.unshift({...base,stage:'Captured'});else st.captures.unshift({...base,kind});save();q('#captureText').value='';q('#captureArea').value='';q('#captureDialog').close();renderAll()};
q('#weeklyNote').oninput=e=>{st.weeklyNote=e.target.value;save()};q('#markReviewed').onclick=()=>{st.lastReviewed=new Date().toISOString();save();renderReview()};function renderReview(){q('#weeklyNote').value=st.weeklyNote||'';q('#reviewStamp').textContent=st.lastReviewed?`Last completed ${new Date(st.lastReviewed).toLocaleString('en-GB')}`:''}
q('#closeDay').onclick=()=>q('#closing').classList.remove('hidden');q('#returnDashboard').onclick=()=>q('#closing').classList.add('hidden');q('#finishClosing').onclick=()=>{st.tomorrowFirst=q('#tomorrowFirst').value.trim();save();q('#closing').classList.add('hidden');alert('Day closed. Your organiser remains available when you return.')};
q('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(st,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`playtrix-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u);status('Backup exported.')};
q('#importData').onclick=async()=>{const f=q('#importFile').files[0];if(!f){status('Choose a JSON backup first.');return}try{const data=JSON.parse(await f.text());if(!data||data.version!==VERSION||!Array.isArray(data.tasks)||!Array.isArray(data.projects)||!Array.isArray(data.waiting)||!Array.isArray(data.ideas)||!Array.isArray(data.tools)||!Array.isArray(data.captures))throw 0;if(!confirm('Replace current Playtrix data with this backup?'))return;st={...blank(),...data};save();renderAll();status('Backup imported.')}catch(e){status('Import rejected: this is not a valid Playtrix v2 backup.')}};
q('#resetData').onclick=()=>{if(confirm('Delete all Playtrix organiser data from this browser? This cannot be undone unless you exported a backup.')){localStorage.removeItem(KEY);st=blank();renderAll();status('Local organiser data reset.')}};
function renderAll(){renderToday();renderTasks();renderWaiting();renderProjects();renderIdeas();renderTools();renderReview()}renderAll();
});