'use strict';
document.addEventListener('DOMContentLoaded',()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const VERSION=3,PRODUCT_VERSION='3.0-pre-market',KEY='playtrix.organiser.v3',PREVIOUS_KEY='playtrix.organiser.v2',CORRUPT_KEY='playtrix.recovery.corrupt';
const now=()=>new Date().toISOString();
const id=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const todayItem=(text='')=>({id:id(),text,done:false});
const blank=()=>({version:VERSION,principal:'',supporting:[],maintenance:[],learning:[],stop:'',tasks:[],projects:[],waiting:[],ideas:[],tools:[],inbox:[],notes:[],weeklyNote:'',lastReviewed:'',tomorrowFirst:'',lastClosed:'',settings:{welcomeSeen:false}});
let st=blank(),storageHealthy=true,taskFilter='open';

const normaliseToday=list=>(Array.isArray(list)?list:[]).map(x=>typeof x==='string'?todayItem(x):({id:x.id||id(),text:String(x.text||''),done:Boolean(x.done)}));
const normaliseCommon=(x,fallback={})=>({...fallback,...x,id:x.id||id(),createdAt:x.createdAt||now(),updatedAt:x.updatedAt||x.createdAt||now()});
function migrateV2(v2){
  const migrated=blank();
  migrated.principal=String(v2.principal||'');
  migrated.supporting=normaliseToday(v2.supporting);
  migrated.maintenance=normaliseToday(v2.maintenance);
  migrated.learning=normaliseToday(v2.formation||v2.learning);
  migrated.stop=String(v2.stop||'');
  migrated.tasks=(v2.tasks||[]).map(x=>normaliseCommon(x,{text:'',status:'Active',notes:'',area:'',projectId:'',due:'',review:''}));
  migrated.projects=(v2.projects||[]).map(x=>normaliseCommon(x,{name:'',status:'Active',purpose:'',position:'',nextAction:'',waitingOn:'',review:'',enoughForNow:'',notes:''}));
  migrated.waiting=(v2.waiting||[]).map(x=>normaliseCommon(x,{text:'',status:'Waiting',notes:'',area:'',projectId:'',dependsOn:'',followUp:'',review:''}));
  migrated.ideas=(v2.ideas||[]).map(x=>normaliseCommon(x,{text:'',stage:'Captured',area:'',notBefore:'',notes:''}));
  migrated.tools=(v2.tools||[]).map(x=>normaliseCommon(x,{name:'',url:'',notes:''}));
  (v2.captures||[]).forEach(x=>{const item=normaliseCommon(x,{text:'',area:'',projectId:'',notes:''});if(x.kind==='reference')migrated.notes.push(item);else migrated.inbox.push(item)});
  migrated.weeklyNote=String(v2.weeklyNote||'');migrated.lastReviewed=String(v2.lastReviewed||'');migrated.tomorrowFirst=String(v2.tomorrowFirst||'');
  return migrated;
}
function validState(x){return Boolean(x&&x.version===VERSION&&['tasks','projects','waiting','ideas','tools','inbox','notes','supporting','maintenance','learning'].every(k=>Array.isArray(x[k])))}
function load(){
  try{
    const raw=localStorage.getItem(KEY);
    if(raw){const parsed=JSON.parse(raw);if(validState(parsed)){st={...blank(),...parsed,settings:{...blank().settings,...(parsed.settings||{})}};return}localStorage.setItem(CORRUPT_KEY,raw);storageHealthy=false;status('Stored organiser data could not be validated. A recovery copy was preserved and a safe empty organiser was opened.');return}
    const old=localStorage.getItem(PREVIOUS_KEY);
    if(old){const parsed=JSON.parse(old);if(parsed&&parsed.version===2){st=migrateV2(parsed);if(save()){status('Playtrix upgraded your existing v2 organiser to the current data model. Export a fresh backup from Settings.');}return}}
  }catch(e){storageHealthy=false;status('Browser storage could not be read safely. Playtrix opened without overwriting stored data.')}
}
function save(){try{localStorage.setItem(KEY,JSON.stringify(st));storageHealthy=true;return true}catch(e){storageHealthy=false;status('Browser storage is unavailable or full. Changes may not persist. Export a backup if possible.');return false}}
function status(t){const el=q('#settingsStatus');if(el)el.textContent=t}
function stamp(x){x.updatedAt=now();return x}
function projectName(pid){return st.projects.find(p=>p.id===pid)?.name||''}
function projectOptions(selected=''){return `<option value="">None</option>`+st.projects.filter(p=>p.status!=='Complete').map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.name)}</option>`).join('')}
function navProjectOptions(){q('#captureProject').innerHTML=projectOptions('')}
function show(v){qa('.view').forEach(x=>x.classList.toggle('active',x.id===v));qa('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));q('#mobileMoreMenu').classList.add('hidden');q('#mobileMore').setAttribute('aria-expanded','false');renderAll();scrollTo(0,0);q('#mainContent').focus({preventScroll:true})}
qa('[data-view]').forEach(x=>x.onclick=()=>show(x.dataset.view));
q('#mobileMore').onclick=()=>{const m=q('#mobileMoreMenu'),open=m.classList.toggle('hidden')===false;q('#mobileMore').setAttribute('aria-expanded',String(open))};
q('#todayHeading').textContent=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});

function renderTodayRows(sel,list,placeholder){const b=q(sel);b.innerHTML='';if(!list.length)b.innerHTML='<p class="empty compact">Nothing chosen here.</p>';list.forEach(item=>{const r=document.createElement('div');r.className='simple-row';r.innerHTML=`<input aria-label="Mark complete" type="checkbox" ${item.done?'checked':''}><input value="${esc(item.text)}" placeholder="${esc(placeholder)}" aria-label="${esc(placeholder)}"><button type="button" class="icon-button" aria-label="Delete">×</button>`;r.children[0].onchange=e=>{item.done=e.target.checked;save()};r.children[1].oninput=e=>{item.text=e.target.value;save()};r.children[2].onclick=()=>{list.splice(list.findIndex(x=>x.id===item.id),1);save();renderToday()};b.append(r)})}
function renderToday(){renderTodayRows('#supportingList',st.supporting,'Supporting action');renderTodayRows('#maintenanceList',st.maintenance,'Life admin or upkeep');renderTodayRows('#learningList',st.learning,'Learning item');q('#principalWork').value=st.principal;q('#stopCondition').value=st.stop;q('#taskCount').textContent=st.tasks.filter(x=>x.status!=='Complete').length;q('#waitingCount').textContent=st.waiting.filter(x=>x.status!=='Complete'&&x.status!=='Cancelled').length;q('#projectCount').textContent=st.projects.filter(x=>x.status!=='Complete'&&x.status!=='Archived').length;q('#inboxCount').textContent=st.inbox.length}
q('#principalWork').oninput=e=>{st.principal=e.target.value;save()};q('#stopCondition').oninput=e=>{st.stop=e.target.value;save()};
q('#addSupporting').onclick=()=>{st.supporting.push(todayItem());save();renderToday()};q('#addMaintenance').onclick=()=>{st.maintenance.push(todayItem());save();renderToday()};q('#addLearning').onclick=()=>{st.learning.push(todayItem());save();renderToday()};

function metaLine(item){const bits=[];if(item.area)bits.push(item.area);if(item.projectId&&projectName(item.projectId))bits.push(projectName(item.projectId));if(item.due)bits.push(`Due ${item.due}`);if(item.followUp)bits.push(`Follow up ${item.followUp}`);if(item.review)bits.push(`Review ${item.review}`);return bits.join(' · ')}
function card(item,type){const a=document.createElement('article');a.className='status-card';const title=item.text||item.name||'Untitled';a.innerHTML=`<span class="eyebrow">${esc(item.status||type)}</span><h3>${esc(title)}</h3>${metaLine(item)?`<small>${esc(metaLine(item))}</small>`:''}${item.notes?`<p>${esc(item.notes)}</p>`:''}<div class="dialog-actions"><button class="ghost edit" type="button">Edit</button><button class="danger del" type="button">Delete</button></div>`;a.querySelector('.edit').onclick=()=>openEdit(type,item);a.querySelector('.del').onclick=()=>removeItem(type,item.id);return a}
function removeItem(type,itemId){if(!confirm('Delete this item?'))return;const map={task:'tasks',waiting:'waiting',project:'projects',note:'notes',inbox:'inbox'};const key=map[type];if(!key)return;st[key]=st[key].filter(x=>x.id!==itemId);save();renderAll()}
function emptyInto(el,text){el.innerHTML=`<p class="empty">${esc(text)}</p>`}
function renderInbox(){const b=q('#inboxList');b.innerHTML='';if(!st.inbox.length)return emptyInto(b,'Inbox clear. Capture something without deciding what it is yet.');st.inbox.forEach(x=>b.append(card(x,'inbox')))}
function dueNow(x){const t=new Date();t.setHours(23,59,59,999);return [x.due,x.review].some(d=>d&&new Date(d)<=t)}
function renderTasks(){const b=q('#taskList');b.innerHTML='';let items=st.tasks;if(taskFilter==='open')items=items.filter(x=>x.status!=='Complete');if(taskFilter==='complete')items=items.filter(x=>x.status==='Complete');if(taskFilter==='due')items=items.filter(x=>x.status!=='Complete'&&dueNow(x));if(!items.length)return emptyInto(b,'No tasks in this view.');items.forEach(x=>b.append(card(x,'task')))}
qa('[data-task-filter]').forEach(btn=>btn.onclick=()=>{taskFilter=btn.dataset.taskFilter;qa('[data-task-filter]').forEach(x=>x.classList.toggle('active',x===btn));renderTasks()});
function renderWaiting(){const b=q('#waitingList');b.innerHTML='';if(!st.waiting.length)return emptyInto(b,'Nothing is waiting on someone or something else.');st.waiting.forEach(x=>b.append(card(x,'waiting')))}
function renderNotes(){const b=q('#noteList');b.innerHTML='';if(!st.notes.length)return emptyInto(b,'No reference notes yet.');st.notes.forEach(x=>b.append(card(x,'note')))}
let selectedProject='';
function renderProjects(){const l=q('#projectList');l.innerHTML='';if(!st.projects.length){q('#projectWorkspace').innerHTML='<p class="empty">No projects yet.</p>';return}st.projects.forEach(p=>{const b=document.createElement('button');b.className='project-button'+(p.id===selectedProject?' active':'');b.type='button';b.innerHTML=`<strong>${esc(p.name)}</strong><span>${esc(p.status)}</span>`;b.onclick=()=>{selectedProject=p.id;renderProjects()};l.append(b)});if(!selectedProject||!st.projects.some(p=>p.id===selectedProject))selectedProject=st.projects[0].id;const p=st.projects.find(x=>x.id===selectedProject);const w=q('#projectWorkspace');w.innerHTML=`<div class="project-head"><span class="eyebrow">${esc(p.status)}</span><h3>${esc(p.name)}</h3>${p.purpose?`<p>${esc(p.purpose)}</p>`:''}</div><div class="project-fields"><div class="project-field"><strong>Current position</strong><p>${esc(p.position||'Not recorded')}</p></div><div class="project-field"><strong>Next action</strong><p>${esc(p.nextAction||'Not recorded')}</p></div><div class="project-field"><strong>Waiting / dependency</strong><p>${esc(p.waitingOn||'None recorded')}</p></div><div class="project-field"><strong>Review trigger</strong><p>${esc(p.review||'None recorded')}</p></div><div class="project-field full"><strong>Enough for now</strong><p>${esc(p.enoughForNow||'Not recorded')}</p></div><div class="project-field full"><strong>Related open tasks</strong><p>${st.tasks.filter(t=>t.projectId===p.id&&t.status!=='Complete').map(t=>esc(t.text)).join('<br>')||'None'}</p></div></div><div class="project-actions"><button class="ghost edit" type="button">Edit project</button><button class="danger del" type="button">Delete</button></div>`;w.querySelector('.edit').onclick=()=>openEdit('project',p);w.querySelector('.del').onclick=()=>removeItem('project',p.id)}
const stages=['Captured','Exploring','Not before','Candidate project','Released'];
function renderIdeas(){const b=q('#kanban');b.innerHTML='';stages.forEach(stage=>{const c=document.createElement('section');c.className='kanban-col';c.innerHTML=`<h3>${stage}</h3><div></div>`;st.ideas.filter(x=>x.stage===stage).forEach(x=>{const a=document.createElement('article');a.className='idea';a.innerHTML=`<h4>${esc(x.text)}</h4>${x.notBefore?`<small>Not before ${esc(x.notBefore)}</small>`:''}<select aria-label="Idea stage">${stages.map(y=>`<option>${esc(y)}</option>`).join('')}</select><div class="idea-actions"><button class="ghost promote" type="button">${stage==='Candidate project'?'Make project':'Make task'}</button><button class="danger" type="button">Delete</button></div>`;a.querySelector('select').value=x.stage;a.querySelector('select').onchange=e=>{x.stage=e.target.value;stamp(x);save();renderIdeas()};a.querySelector('.danger').onclick=()=>{st.ideas=st.ideas.filter(y=>y.id!==x.id);save();renderIdeas()};a.querySelector('.promote').onclick=()=>{if(stage==='Candidate project'){st.projects.unshift(normaliseCommon({name:x.text,purpose:x.notes||'',status:'Active',position:'',nextAction:'',waitingOn:'',review:'',enoughForNow:'',notes:''}));selectedProject=st.projects[0].id}else{st.tasks.unshift(normaliseCommon({text:x.text,status:'Active',notes:x.notes||'',area:x.area||'',projectId:'',due:'',review:''}))}x.stage='Released';stamp(x);save();renderAll()};c.querySelector('div').append(a)});b.append(c)})}
function renderTools(){const b=q('#toolGroups');b.innerHTML='';if(!st.tools.length)return emptyInto(b,'Add links to tools and workspaces you use.');st.tools.forEach(x=>{const a=document.createElement('article');a.className='desk-card';a.innerHTML=`<div><h4>${esc(x.name)}</h4><small>${esc(x.url)}</small>${x.notes?`<p>${esc(x.notes)}</p>`:''}</div><div class="tool-actions"><a class="ghost" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open</a><button class="ghost edit" type="button">Edit</button><button class="danger del" type="button">Delete</button></div>`;a.querySelector('.edit').onclick=()=>openEdit('tool',x);a.querySelector('.del').onclick=()=>{if(confirm('Delete this tool?')){st.tools=st.tools.filter(y=>y.id!==x.id);save();renderTools()}};b.append(a)})}
function renderReview(){q('#weeklyNote').value=st.weeklyNote||'';q('#reviewStamp').textContent=st.lastReviewed?`Last completed ${new Date(st.lastReviewed).toLocaleString('en-GB')}`:'';const staleDate=Date.now()-14*86400000;const staleTasks=st.tasks.filter(x=>x.status!=='Complete'&&new Date(x.updatedAt||x.createdAt).getTime()<staleDate).length;const projectsNoNext=st.projects.filter(x=>x.status!=='Complete'&&!x.nextAction&&!x.enoughForNow).length;const waitingDue=st.waiting.filter(x=>x.status==='Waiting'&&x.followUp&&new Date(x.followUp)<=new Date()).length;const s=q('#reviewSignals');s.innerHTML=`<article><strong>${st.inbox.length}</strong><span>unprocessed captures</span></article><article><strong>${staleTasks}</strong><span>stale open tasks</span></article><article><strong>${projectsNoNext}</strong><span>projects without next action / enough-for-now</span></article><article><strong>${waitingDue}</strong><span>waiting follow-ups due</span></article>`}

function addTask(seed=''){const item=normaliseCommon({text:seed,status:'Active',notes:'',area:'',projectId:'',due:'',review:''});st.tasks.unshift(item);save();openEdit('task',item)}
function addWaiting(seed=''){const item=normaliseCommon({text:seed,status:'Waiting',notes:'',area:'',projectId:'',dependsOn:'',followUp:'',review:''});st.waiting.unshift(item);save();openEdit('waiting',item)}
function addProject(seed=''){const item=normaliseCommon({name:seed,status:'Active',purpose:'',position:'',nextAction:'',waitingOn:'',review:'',enoughForNow:'',notes:''});st.projects.unshift(item);selectedProject=item.id;save();openEdit('project',item)}
function addNote(seed=''){const item=normaliseCommon({text:seed,notes:'',area:'',projectId:''});st.notes.unshift(item);save();openEdit('note',item)}
q('#addTask').onclick=()=>addTask();q('#addWaiting').onclick=()=>addWaiting();q('#addProject').onclick=()=>addProject();q('#addNote').onclick=()=>addNote();
q('#addIdea').onclick=()=>{const x=prompt('Idea');if(x){st.ideas.unshift(normaliseCommon({text:x,stage:'Captured',area:'',notBefore:'',notes:''}));save();renderIdeas()}};
q('#addTool').onclick=()=>{const item=normaliseCommon({name:'',url:'',notes:''});st.tools.push(item);save();openEdit('tool',item)};

let editCtx=null;
const field=(label,name,value='',type='text',extra='')=>`<label>${label}<input id="edit_${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const areaField=x=>field('Area / context','area',x.area||'');
const projectField=x=>`<label>Project<select id="edit_projectId">${projectOptions(x.projectId||'')}</select></label>`;
function openEdit(type,item){editCtx={type,item};q('#editTitle').textContent=`Edit ${type==='note'?'note':type}`;let html='';if(type==='task')html=field('Task','text',item.text)+`<label>Notes<textarea id="edit_notes" rows="4">${esc(item.notes||'')}</textarea></label>`+`<label>Status<select id="edit_status">${['Active','Waiting','Complete'].map(s=>`<option ${s===item.status?'selected':''}>${s}</option>`).join('')}</select></label>`+areaField(item)+projectField(item)+field('Due date','due',item.due||'','date')+field('Review date','review',item.review||'','date');
else if(type==='waiting')html=field('What are you waiting for?','text',item.text)+field('Depends on','dependsOn',item.dependsOn||'')+`<label>Notes<textarea id="edit_notes" rows="4">${esc(item.notes||'')}</textarea></label>`+`<label>Status<select id="edit_status">${['Waiting','Actionable','Complete','Cancelled'].map(s=>`<option ${s===item.status?'selected':''}>${s}</option>`).join('')}</select></label>`+areaField(item)+projectField(item)+field('Follow-up date','followUp',item.followUp||'','date')+field('Review date','review',item.review||'','date');
else if(type==='project')html=field('Project','name',item.name)+field('Purpose','purpose',item.purpose||'')+field('Current position','position',item.position||'')+field('Next action','nextAction',item.nextAction||'')+field('Waiting / dependency','waitingOn',item.waitingOn||'')+field('Review trigger','review',item.review||'')+field('Enough for now','enoughForNow',item.enoughForNow||'')+`<label>Notes<textarea id="edit_notes" rows="4">${esc(item.notes||'')}</textarea></label>`+`<label>Status<select id="edit_status">${['Active','Waiting','Maintenance','Paused','Complete','Archived'].map(s=>`<option ${s===item.status?'selected':''}>${s}</option>`).join('')}</select></label>`;
else if(type==='note')html=field('Title','text',item.text)+`<label>Note<textarea id="edit_notes" rows="7">${esc(item.notes||'')}</textarea></label>`+areaField(item)+projectField(item);
else if(type==='inbox')html=field('Capture','text',item.text)+`<label>Notes<textarea id="edit_notes" rows="4">${esc(item.notes||'')}</textarea></label>`+areaField(item)+`<label>Convert to<select id="edit_convert"><option value="">Keep in Inbox</option><option value="task">Task</option><option value="waiting">Waiting</option><option value="note">Note</option><option value="idea">Idea</option></select></label>`;
else if(type==='tool')html=field('Tool name','name',item.name)+field('Web address','url',item.url||'','url','placeholder="https://..."')+`<label>Notes<textarea id="edit_notes" rows="4">${esc(item.notes||'')}</textarea></label>`;
q('#editFields').innerHTML=html;q('#editStatusMessage').textContent='';q('#editDialog').showModal();setTimeout(()=>q('#editFields input, #editFields textarea, #editFields select')?.focus(),0)}
function read(id){return q(`#edit_${id}`)?.value?.trim()||''}
q('#saveEdit').onclick=()=>{if(!editCtx)return;const {type,item}=editCtx;try{
 if(type==='task'){item.text=read('text');if(!item.text)throw new Error('Task title is required.');item.notes=read('notes');item.status=read('status');item.area=read('area');item.projectId=read('projectId');item.due=read('due');item.review=read('review')}
 if(type==='waiting'){item.text=read('text');if(!item.text)throw new Error('Waiting item is required.');item.dependsOn=read('dependsOn');item.notes=read('notes');item.status=read('status');item.area=read('area');item.projectId=read('projectId');item.followUp=read('followUp');item.review=read('review');if(item.status==='Actionable'){st.tasks.unshift(normaliseCommon({text:item.text,status:'Active',notes:item.notes,area:item.area,projectId:item.projectId,due:'',review:item.review}));item.status='Complete'}}
 if(type==='project'){item.name=read('name');if(!item.name)throw new Error('Project name is required.');item.purpose=read('purpose');item.position=read('position');item.nextAction=read('nextAction');item.waitingOn=read('waitingOn');item.review=read('review');item.enoughForNow=read('enoughForNow');item.notes=read('notes');item.status=read('status')}
 if(type==='note'){item.text=read('text');if(!item.text)throw new Error('Note title is required.');item.notes=read('notes');item.area=read('area');item.projectId=read('projectId')}
 if(type==='inbox'){item.text=read('text');if(!item.text)throw new Error('Capture text is required.');item.notes=read('notes');item.area=read('area');const convert=read('convert');if(convert){if(convert==='task')st.tasks.unshift(normaliseCommon({text:item.text,status:'Active',notes:item.notes,area:item.area,projectId:'',due:'',review:''}));if(convert==='waiting')st.waiting.unshift(normaliseCommon({text:item.text,status:'Waiting',notes:item.notes,area:item.area,projectId:'',dependsOn:'',followUp:'',review:''}));if(convert==='note')st.notes.unshift(normaliseCommon({text:item.text,notes:item.notes,area:item.area,projectId:''}));if(convert==='idea')st.ideas.unshift(normaliseCommon({text:item.text,stage:'Captured',area:item.area,notBefore:'',notes:item.notes}));st.inbox=st.inbox.filter(x=>x.id!==item.id)}}
 if(type==='tool'){item.name=read('name');if(!item.name)throw new Error('Tool name is required.');const url=read('url');const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error('Use an http or https web address.');item.url=u.href;item.notes=read('notes')}
 stamp(item);if(!save())throw new Error('Could not save to browser storage.');q('#editDialog').close();renderAll();
 }catch(e){q('#editStatusMessage').textContent=e.message||'Please check the fields and try again.'}}

function openCapture(){navProjectOptions();q('#captureStatus').textContent='';q('#captureDialog').showModal();setTimeout(()=>q('#captureText').focus(),0)}
q('#captureButton').onclick=openCapture;q('#mobileCapture').onclick=openCapture;q('#mobileNavCapture').onclick=openCapture;
q('#saveCapture').onclick=()=>{const text=q('#captureText').value.trim();if(!text){q('#captureStatus').textContent='Write something before saving.';return}const kind=q('#captureKind').value,area=q('#captureArea').value.trim(),projectId=q('#captureProject').value,base=normaliseCommon({text,area,projectId,notes:''});if(kind==='task')st.tasks.unshift({...base,status:'Active',due:'',review:''});else if(kind==='waiting')st.waiting.unshift({...base,status:'Waiting',dependsOn:'',followUp:'',review:''});else if(kind==='idea')st.ideas.unshift({...base,stage:'Captured',notBefore:''});else if(kind==='note')st.notes.unshift(base);else st.inbox.unshift(base);if(!save()){q('#captureStatus').textContent='Could not save. Your text is still here so you can copy it.';return}q('#captureText').value='';q('#captureArea').value='';q('#captureProject').value='';q('#captureDialog').close();renderAll()};

q('#weeklyNote').oninput=e=>{st.weeklyNote=e.target.value;save()};q('#markReviewed').onclick=()=>{st.lastReviewed=now();save();renderReview()};
function unresolvedToday(){return [['Supporting',st.supporting],['Maintenance',st.maintenance],['Learning',st.learning]].flatMap(([group,list])=>list.filter(x=>x.text.trim()&&!x.done).map(x=>({group,item:x,list})))}
q('#closeDay').onclick=()=>{const wrap=q('#dayCloseItems');wrap.innerHTML='';const unresolved=unresolvedToday();if(!unresolved.length)wrap.innerHTML='<p class="empty compact">No unfinished Today items.</p>';unresolved.forEach(({group,item})=>{const row=document.createElement('div');row.className='day-close-row';row.innerHTML=`<div><strong>${esc(item.text)}</strong><small>${esc(group)}</small></div><label>Disposition<select data-day-id="${esc(item.id)}"><option value="keep">Keep on Today</option><option value="task">Move to Tasks</option><option value="complete">Mark complete</option><option value="remove">Remove</option></select></label>`;wrap.append(row)});q('#tomorrowFirst').value=st.tomorrowFirst||'';q('#dayCloseStatus').textContent='';q('#dayClose').classList.remove('hidden');q('#dayClose').querySelector('select, input, button')?.focus()};
q('#returnDashboard').onclick=()=>q('#dayClose').classList.add('hidden');
q('#finishClosing').onclick=()=>{qa('[data-day-id]').forEach(sel=>{const target=[st.supporting,st.maintenance,st.learning].flat().find(x=>x.id===sel.dataset.dayId);if(!target)return;const lists=[st.supporting,st.maintenance,st.learning];if(sel.value==='task'){st.tasks.unshift(normaliseCommon({text:target.text,status:'Active',notes:'',area:'',projectId:'',due:'',review:''}));lists.forEach(list=>{const i=list.findIndex(x=>x.id===target.id);if(i>=0)list.splice(i,1)})}if(sel.value==='complete')target.done=true;if(sel.value==='remove')lists.forEach(list=>{const i=list.findIndex(x=>x.id===target.id);if(i>=0)list.splice(i,1)})});st.tomorrowFirst=q('#tomorrowFirst').value.trim();st.lastClosed=now();if(save()){q('#dayClose').classList.add('hidden');renderAll();status('Day closed deliberately. Unfinished items were handled using your chosen dispositions.')}else q('#dayCloseStatus').textContent='Could not save the closing decisions. Nothing has been cleared.'};

q('#exportData').onclick=()=>{const payload={...st,exportedAt:now(),productVersion:PRODUCT_VERSION};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`playtrix-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u);status('Backup exported.')};
q('#importData').onclick=async()=>{const f=q('#importFile').files[0];if(!f){status('Choose a JSON backup first.');return}if(f.size>5*1024*1024){status('Import rejected: backup is larger than the 5 MB safety limit.');return}try{const data=JSON.parse(await f.text());let candidate;if(data.version===VERSION&&validState(data))candidate={...blank(),...data,settings:{...blank().settings,...(data.settings||{})}};else if(data.version===2)candidate=migrateV2(data);else throw new Error('Unsupported or invalid Playtrix backup.');if(!confirm('Replace current Playtrix data with this validated backup? Export your current organiser first if you need a recovery copy.'))return;const previous=st;st=candidate;if(!save()){st=previous;throw new Error('Browser storage could not save the imported organiser. Current in-memory data was kept.')}renderAll();status('Backup imported successfully.')}catch(e){status(`Import rejected: ${e.message||'invalid backup'}`)}};
q('#resetData').onclick=()=>{if(confirm('Delete all current Playtrix organiser data from this browser? This cannot be undone unless you exported a backup.')){try{localStorage.removeItem(KEY);st=blank();renderAll();status('Local organiser data reset.')}catch(e){status('Reset could not be completed because browser storage is unavailable.')}}};

q('#globalSearch').oninput=e=>renderSearch(e.target.value);q('#clearSearch').onclick=()=>{q('#globalSearch').value='';renderSearch('')};
function renderSearch(term){const box=q('#searchResults'),t=term.trim().toLowerCase();if(!t){box.classList.add('hidden');box.innerHTML='';return}const hits=[];const add=(type,items,label)=>items.forEach(x=>{const hay=[x.text,x.name,x.notes,x.area,x.purpose,x.position,x.nextAction,x.dependsOn].filter(Boolean).join(' ').toLowerCase();if(hay.includes(t))hits.push({type,label,item:x})});add('task',st.tasks,'Task');add('project',st.projects,'Project');add('waiting',st.waiting,'Waiting');add('note',st.notes,'Note');add('idea',st.ideas,'Not Yet');add('inbox',st.inbox,'Inbox');box.classList.remove('hidden');box.innerHTML=hits.length?`<h2>Search results</h2><div class="search-grid">${hits.slice(0,100).map(h=>`<button type="button" data-search-type="${esc(h.type)}" data-search-id="${esc(h.item.id)}"><span>${esc(h.label)}</span><strong>${esc(h.item.text||h.item.name)}</strong></button>`).join('')}</div>`:'<p>No matching organiser items.</p>';qa('[data-search-id]').forEach(btn=>btn.onclick=()=>{const type=btn.dataset.searchType,idv=btn.dataset.searchId;if(type==='project'){selectedProject=idv;show('projects')}else{const view={task:'tasks',waiting:'waiting',note:'notes',idea:'notyet',inbox:'inbox'}[type];if(view)show(view)}})}

q('#productVersion').textContent=PRODUCT_VERSION;q('#schemaVersion').textContent=String(VERSION);
function renderAll(){renderToday();renderInbox();renderTasks();renderWaiting();renderNotes();renderProjects();renderIdeas();renderTools();renderReview();navProjectOptions()}
load();renderAll();if(!storageHealthy)q('#storageNotice').classList.add('warning');
});
